IF NOT EXISTS (
    SELECT 1
    FROM sys.objects
    WHERE object_id = OBJECT_ID(N'[dbo].[MEMBER_FAVORITE_PRODUCT]')
      AND type in (N'U')
)
BEGIN
    CREATE TABLE [dbo].[MEMBER_FAVORITE_PRODUCT] (
        [FavoriteID] INT IDENTITY(1,1) NOT NULL,
        [MemberID] INT NOT NULL,
        [ProductID] INT NOT NULL,
        [CreatedAt] DATETIME2 NOT NULL CONSTRAINT [DF_MEMBER_FAVORITE_PRODUCT_CreatedAt] DEFAULT (DATEADD(hour, 7, GETUTCDATE())),
        CONSTRAINT [PK_MEMBER_FAVORITE_PRODUCT] PRIMARY KEY CLUSTERED ([FavoriteID] ASC),
        CONSTRAINT [FK_MEMBER_FAVORITE_PRODUCT_MEMBER] FOREIGN KEY ([MemberID]) REFERENCES [dbo].[MEMBER] ([MemberID]) ON DELETE CASCADE,
        CONSTRAINT [FK_MEMBER_FAVORITE_PRODUCT_PRODUCT] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[PRODUCT] ([ProductID]) ON DELETE CASCADE
    );

    CREATE UNIQUE INDEX [IX_MEMBER_FAVORITE_PRODUCT_Member_Product]
        ON [dbo].[MEMBER_FAVORITE_PRODUCT] ([MemberID], [ProductID]);
END
