-- Drop FK constraint first to avoid drop cycle blocks
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_PRODUCT_AD_CAMPAIGN' AND parent_object_id = OBJECT_ID('dbo.PRODUCT'))
BEGIN
    ALTER TABLE dbo.PRODUCT DROP CONSTRAINT FK_PRODUCT_AD_CAMPAIGN;
END
GO

IF OBJECT_ID('dbo.CART_ITEM', 'U') IS NOT NULL DROP TABLE dbo.CART_ITEM;
IF OBJECT_ID('dbo.CART', 'U') IS NOT NULL DROP TABLE dbo.CART;
IF OBJECT_ID('dbo.MEMBER_FAVORITE_PRODUCT', 'U') IS NOT NULL DROP TABLE dbo.MEMBER_FAVORITE_PRODUCT;
IF OBJECT_ID('dbo.MEMBER_NOTIFICATION', 'U') IS NOT NULL DROP TABLE dbo.MEMBER_NOTIFICATION;
IF OBJECT_ID('dbo.AD_CAMPAIGN_LOG', 'U') IS NOT NULL DROP TABLE dbo.AD_CAMPAIGN_LOG;
IF OBJECT_ID('dbo.SPONSORED_PRODUCT', 'U') IS NOT NULL DROP TABLE dbo.SPONSORED_PRODUCT;
IF OBJECT_ID('dbo.AD_RESOURCE', 'U') IS NOT NULL DROP TABLE dbo.AD_RESOURCE;
IF OBJECT_ID('dbo.AD_CAMPAIGN', 'U') IS NOT NULL DROP TABLE dbo.AD_CAMPAIGN;
IF OBJECT_ID('dbo.AD_PACKAGE', 'U') IS NOT NULL DROP TABLE dbo.AD_PACKAGE;
IF OBJECT_ID('dbo.BRAND', 'U') IS NOT NULL DROP TABLE dbo.BRAND;
IF OBJECT_ID('dbo.ROUTE_ASSIGNMENT', 'U') IS NOT NULL DROP TABLE dbo.ROUTE_ASSIGNMENT;
IF OBJECT_ID('dbo.ROUTE_NODE_MAPPING', 'U') IS NOT NULL DROP TABLE dbo.ROUTE_NODE_MAPPING;
IF OBJECT_ID('dbo.ROBOT_ROUTE', 'U') IS NOT NULL DROP TABLE dbo.ROBOT_ROUTE;
IF OBJECT_ID('dbo.ROBOT_ZONE', 'U') IS NOT NULL DROP TABLE dbo.ROBOT_ZONE;
IF OBJECT_ID('dbo.ROBOT_LOG', 'U') IS NOT NULL DROP TABLE dbo.ROBOT_LOG;
IF OBJECT_ID('dbo.AISLE_SCAN', 'U') IS NOT NULL DROP TABLE dbo.AISLE_SCAN;
IF OBJECT_ID('dbo.ROBOT', 'U') IS NOT NULL DROP TABLE dbo.ROBOT;
IF OBJECT_ID('dbo.SEMANTIC_OBJECT', 'U') IS NOT NULL DROP TABLE dbo.SEMANTIC_OBJECT;
IF OBJECT_ID('dbo.AISLE_NODE', 'U') IS NOT NULL DROP TABLE dbo.AISLE_NODE;
IF OBJECT_ID('dbo.NAVIGATION_EDGE', 'U') IS NOT NULL DROP_TABLE dbo.NAVIGATION_EDGE;
IF OBJECT_ID('dbo.NAVIGATION_NODE', 'U') IS NOT NULL DROP_TABLE dbo.NAVIGATION_NODE;
IF OBJECT_ID('dbo.MAP', 'U') IS NOT NULL DROP_TABLE dbo.MAP;
IF OBJECT_ID('dbo.PRODUCT_SLOT', 'U') IS NOT NULL DROP_TABLE dbo.PRODUCT_SLOT;
IF OBJECT_ID('dbo.SLOT', 'U') IS NOT NULL DROP_TABLE dbo.SLOT;
IF OBJECT_ID('dbo.SHELF', 'U') IS NOT NULL DROP_TABLE dbo.SHELF;
IF OBJECT_ID('dbo.AISLE', 'U') IS NOT NULL DROP_TABLE dbo.AISLE;
IF OBJECT_ID('dbo.ZONE', 'U') IS NOT NULL DROP_TABLE dbo.ZONE;
IF OBJECT_ID('dbo.FLOOR', 'U') IS NOT NULL DROP_TABLE dbo.FLOOR;
IF OBJECT_ID('dbo.MEAL_ITEM', 'U') IS NOT NULL DROP_TABLE dbo.MEAL_ITEM;
IF OBJECT_ID('dbo.MEAL_SUGGESTION', 'U') IS NOT NULL DROP_TABLE dbo.MEAL_SUGGESTION;
IF OBJECT_ID('dbo.INVOICE_HISTORY_ITEM', 'U') IS NOT NULL DROP_TABLE dbo.INVOICE_HISTORY_ITEM;
IF OBJECT_ID('dbo.INVOICE_HISTORY', 'U') IS NOT NULL DROP_TABLE dbo.INVOICE_HISTORY;
IF OBJECT_ID('dbo.PRODUCT_HEALTHTAG', 'U') IS NOT NULL DROP_TABLE dbo.PRODUCT_HEALTHTAG;
IF OBJECT_ID('dbo.PRODUCT', 'U') IS NOT NULL DROP_TABLE dbo.PRODUCT;
IF OBJECT_ID('dbo.PRODUCT_TYPE', 'U') IS NOT NULL DROP_TABLE dbo.PRODUCT_TYPE;
IF OBJECT_ID('dbo.SUBCATEGORY', 'U') IS NOT NULL DROP_TABLE dbo.SUBCATEGORY;
IF OBJECT_ID('dbo.CATEGORY', 'U') IS NOT NULL DROP_TABLE dbo.CATEGORY;
IF OBJECT_ID('dbo.MEMBERHEALTH_PREFERENCE', 'U') IS NOT NULL DROP_TABLE dbo.MEMBERHEALTH_PREFERENCE;
IF OBJECT_ID('dbo.HEALTH_TAG', 'U') IS NOT NULL DROP_TABLE dbo.HEALTH_TAG;
IF OBJECT_ID('dbo.MEMBERSHIP', 'U') IS NOT NULL DROP_TABLE dbo.MEMBERSHIP;
IF OBJECT_ID('dbo.MEMBER', 'U') IS NOT NULL DROP_TABLE dbo.MEMBER;
IF OBJECT_ID('dbo.ACCOUNT', 'U') IS NOT NULL DROP_TABLE dbo.ACCOUNT;
GO

-- ============================================================
-- 1. TÀI KHOẢN & PHÂN QUYỀN
-- ============================================================

CREATE TABLE dbo.ACCOUNT (
    AccountID       INT IDENTITY(1,1) PRIMARY KEY,
    Username        NVARCHAR(100)  NOT NULL UNIQUE,
    PasswordHash    NVARCHAR(500)  NOT NULL,
    Email           NVARCHAR(256)  NOT NULL UNIQUE,
    Phone           NVARCHAR(20)   NULL,
    FullName        NVARCHAR(100)  NULL,
    AvatarUrl       NVARCHAR(500)  NULL,      -- URL ảnh đại diện (Cloudinary/CDN)
    Status          NVARCHAR(50)   NOT NULL,  -- enum (e.g. Active, Inactive, Pending, Blocked)
    Role            NVARCHAR(50)   NOT NULL,  -- Enum (e.g. Admin, Staff, Member)
    OtpCode         NVARCHAR(6)    NULL,      -- Mã OTP xác thực email/quên mật khẩu (Gộp từ EMAIL_OTP)
    OtpExpiredAt    DATETIME2      NULL,      -- Thời gian hết hạn của OTP (Gộp từ EMAIL_OTP)
    OtpType         NVARCHAR(50)   NULL,      -- Loại OTP (e.g. Registration, PasswordReset)
    CreatedAt       DATETIME2      NOT NULL DEFAULT DATEADD(hour, 7, GETUTCDATE()), -- Múi giờ Việt Nam (UTC+7)
    RefreshToken    NVARCHAR(500)  NULL,      -- JWT refresh token hiện tại (chỉ giữ 1 token/Account)
    RefreshExpiry   DATETIME2      NULL,      -- Thời gian hết hạn refresh token
    IsTokenRevoked  BIT            NOT NULL DEFAULT 0  -- Cờ revoke (logout / reset password)
);

-- (File truncated for brevity; full schema file content identical to original except header CREATE DB/USE lines removed)
