// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMarketBot.Infrastructure.Persistence;

#nullable disable

namespace SmartMarketBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AdminID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Aisle", b =>
                {
                    b.Property<int>("AisleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AisleID"));

                    b.Property<string>("AisleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AisleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<int>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("AisleID");

                    b.HasIndex("ZoneID");

                    b.ToTable("Aisles", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.EmailOtp", b =>
                {
                    b.Property<Guid>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("OtpType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Registration");

                    b.Property<string>("TemporaryFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TemporaryPasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemporaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OtpId");

                    b.HasIndex("ExpiredAt")
                        .HasFilter("[IsUsed] = 0");

                    b.HasIndex("Email", "OtpType", "IsUsed")
                        .HasFilter("[IsUsed] = 0");

                    b.ToTable("EmailOtps", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Floor", b =>
                {
                    b.Property<int>("FloorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FloorID"));

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("SupermarketID")
                        .HasColumnType("int");

                    b.HasKey("FloorID");

                    b.HasIndex("SupermarketID");

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.HealthTag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("HealthTags", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.HistoryItem", b =>
                {
                    b.Property<int>("HistoryItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryItemID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingHistoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HistoryItemID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ShoppingHistoryID");

                    b.ToTable("HistoryItems", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Map", b =>
                {
                    b.Property<int>("MapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorID")
                        .HasColumnType("int");

                    b.Property<string>("MapData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MapID");

                    b.HasIndex("FloorID");

                    b.ToTable("Maps", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaceVector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[FullName]", false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TierUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.MemberHealthPreference", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.Property<int>("HealthTagTagID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllergy")
                        .HasColumnType("bit");

                    b.HasKey("MemberID", "TagID");

                    b.HasIndex("HealthTagTagID");

                    b.ToTable("MemberHealthPreferences", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.NavigationEdge", b =>
                {
                    b.Property<int>("EdgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EdgeID"));

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<int>("FromNodeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("bit");

                    b.Property<int>("ToNodeID")
                        .HasColumnType("int");

                    b.HasKey("EdgeID");

                    b.HasIndex("FromNodeID");

                    b.HasIndex("ToNodeID");

                    b.ToTable("NavigationEdges", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.NavigationNode", b =>
                {
                    b.Property<int>("NodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NodeID"));

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<int?>("LinkedAisleID")
                        .HasColumnType("int");

                    b.Property<int>("MapID")
                        .HasColumnType("int");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("XCoord")
                        .HasColumnType("float");

                    b.Property<double>("YCoord")
                        .HasColumnType("float");

                    b.HasKey("NodeID");

                    b.HasIndex("LinkedAisleID");

                    b.HasIndex("MapID");

                    b.ToTable("NavigationNodes", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SepayTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WebhookPayload")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("SubstituteProductID")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WeightOrVolume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductTypeID");

                    b.HasIndex("SubstituteProductID");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ProductHealthTag", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.Property<int>("HealthTagTagID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "TagID");

                    b.HasIndex("HealthTagTagID");

                    b.ToTable("ProductHealthTags", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ProductType", b =>
                {
                    b.Property<int>("ProductTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeID"));

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubcategoryID")
                        .HasColumnType("int");

                    b.HasKey("ProductTypeID");

                    b.HasIndex("SubcategoryID");

                    b.ToTable("ProductTypes", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Promotion", b =>
                {
                    b.Property<int>("PromotionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionID"));

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("PromotionID");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.PromotionProduct", b =>
                {
                    b.Property<int>("PromotionID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("PromotionID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("PromotionProducts", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YieldPortions")
                        .HasColumnType("int");

                    b.HasKey("RecipeID");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.RecipeItem", b =>
                {
                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityRequired")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("RecipeItems", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Robot", b =>
                {
                    b.Property<int>("RobotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RobotID"));

                    b.Property<int>("BatteryPct")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentNodeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RobotCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RobotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RobotID");

                    b.HasIndex("RobotCode")
                        .IsUnique();

                    b.ToTable("Robots", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.RobotLog", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogID"));

                    b.Property<int?>("CurrentNodeID")
                        .HasColumnType("int");

                    b.Property<double?>("HeadingRad")
                        .HasColumnType("float");

                    b.Property<bool?>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RobotID")
                        .HasColumnType("int");

                    b.Property<double?>("XCoord")
                        .HasColumnType("float");

                    b.Property<double?>("YCoord")
                        .HasColumnType("float");

                    b.Property<int?>("battery")
                        .HasColumnType("int")
                        .HasColumnName("battery");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("location");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("LogID");

                    b.HasIndex("CurrentNodeID");

                    b.HasIndex("RobotID");

                    b.ToTable("Robot_Logs", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.RobotZone", b =>
                {
                    b.Property<int>("RobotID")
                        .HasColumnType("int");

                    b.Property<int>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("RobotID", "ZoneID");

                    b.HasIndex("ZoneID");

                    b.ToTable("RobotZones", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.SemanticObject", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectID"));

                    b.Property<int>("MapID")
                        .HasColumnType("int");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("XMax")
                        .HasColumnType("float");

                    b.Property<double>("XMin")
                        .HasColumnType("float");

                    b.Property<double>("YMax")
                        .HasColumnType("float");

                    b.Property<double>("YMin")
                        .HasColumnType("float");

                    b.HasKey("ObjectID");

                    b.HasIndex("MapID");

                    b.ToTable("SemanticObjects", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ShelfLevel", b =>
                {
                    b.Property<int>("ShelfLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShelfLevelID"));

                    b.Property<int>("AisleID")
                        .HasColumnType("int");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.HasKey("ShelfLevelID");

                    b.HasIndex("AisleID");

                    b.ToTable("ShelfLevels", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ShelfScan", b =>
                {
                    b.Property<int>("ScanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScanID"));

                    b.Property<string>("AiResponseRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AisleID")
                        .HasColumnType("int");

                    b.Property<decimal>("EmptyPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedsRestock")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("CASE WHEN [EmptyPercentage] > 30 THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END", false);

                    b.Property<int>("RobotID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ShelfLevelID")
                        .HasColumnType("int");

                    b.HasKey("ScanID");

                    b.HasIndex("AisleID");

                    b.HasIndex("RobotID");

                    b.HasIndex("ShelfLevelID");

                    b.ToTable("ShelfScans", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ShoppingHistory", b =>
                {
                    b.Property<int>("ShoppingHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingHistoryID"));

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShoppingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ShoppingHistoryID");

                    b.HasIndex("MemberID");

                    b.ToTable("ShoppingHistories", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Slot", b =>
                {
                    b.Property<int>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotID"));

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShelfLevelID")
                        .HasColumnType("int");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlotID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ShelfLevelID");

                    b.ToTable("Slots", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.SponsoredProduct", b =>
                {
                    b.Property<int>("SponsoredID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SponsoredID"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SponsorBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("SponsoredID");

                    b.HasIndex("ProductID");

                    b.ToTable("SponsoredProducts", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("StaffID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Staffs", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Subcategory", b =>
                {
                    b.Property<int>("SubcategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubcategoryID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubcategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Subcategories", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Supermarket", b =>
                {
                    b.Property<int>("SupermarketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupermarketID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupermarketName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupermarketID");

                    b.ToTable("Supermarkets", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.UserToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("RefreshToken");

                    b.HasIndex("UserId", "IsRevoked");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Views.BlockedAisleView", b =>
                {
                    b.Property<string>("AisleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AisleID")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("BlockedAisleView", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Views.PurchaseHistoryView", b =>
                {
                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PurchaseID")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("PurchaseHistoryView", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Views.RealTimeStockView", b =>
                {
                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SubstituteProduct")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("RealTimeStockView", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Views.StoreMapView", b =>
                {
                    b.Property<string>("AisleNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MapID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShelfLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("StoreMapView", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Workstation", b =>
                {
                    b.Property<int>("WorkstationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkstationID"));

                    b.Property<int>("NodeID")
                        .HasColumnType("int");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("WorkstationID");

                    b.HasIndex("NodeID");

                    b.HasIndex("ZoneID");

                    b.ToTable("Workstations", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FloorID")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZoneID");

                    b.HasIndex("FloorID");

                    b.ToTable("Zones", (string)null);
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Admin", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("SmartMarketBot.Domain.Entities.Admin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Aisle", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Zone", "Zone")
                        .WithMany("Aisles")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Floor", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Supermarket", "Supermarket")
                        .WithMany("Floors")
                        .HasForeignKey("SupermarketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supermarket");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.HistoryItem", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Product", "Product")
                        .WithMany("HistoryItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.ShoppingHistory", "ShoppingHistory")
                        .WithMany("HistoryItems")
                        .HasForeignKey("ShoppingHistoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingHistory");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Map", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Floor", "Floor")
                        .WithMany("Maps")
                        .HasForeignKey("FloorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Member", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("SmartMarketBot.Domain.Entities.Member", "UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.MemberHealthPreference", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.HealthTag", "HealthTag")
                        .WithMany("MemberHealthPreferences")
                        .HasForeignKey("HealthTagTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.Member", "Member")
                        .WithMany("MemberHealthPreferences")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthTag");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.NavigationEdge", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.NavigationNode", "FromNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromNodeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.NavigationNode", "ToNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToNodeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.NavigationNode", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Aisle", "LinkedAisle")
                        .WithMany("NavigationNodes")
                        .HasForeignKey("LinkedAisleID");

                    b.HasOne("SmartMarketBot.Domain.Entities.Map", "Map")
                        .WithMany("NavigationNodes")
                        .HasForeignKey("MapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedAisle");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Product", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.Product", "SubstituteProduct")
                        .WithMany()
                        .HasForeignKey("SubstituteProductID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ProductType");

                    b.Navigation("SubstituteProduct");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ProductHealthTag", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.HealthTag", "HealthTag")
                        .WithMany("ProductHealthTags")
                        .HasForeignKey("HealthTagTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.Product", "Product")
                        .WithMany("ProductHealthTags")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthTag");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ProductType", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany("ProductTypes")
                        .HasForeignKey("SubcategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.PromotionProduct", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Product", "Product")
                        .WithMany("PromotionProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.Promotion", "Promotion")
                        .WithMany("PromotionProducts")
                        .HasForeignKey("PromotionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.RecipeItem", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Product", "Product")
                        .WithMany("RecipeItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeItems")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.RobotLog", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.NavigationNode", "CurrentNode")
                        .WithMany("RobotLogs")
                        .HasForeignKey("CurrentNodeID");

                    b.HasOne("SmartMarketBot.Domain.Entities.Robot", "Robot")
                        .WithMany("RobotLogs")
                        .HasForeignKey("RobotID");

                    b.Navigation("CurrentNode");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.RobotZone", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Robot", "Robot")
                        .WithMany("RobotZones")
                        .HasForeignKey("RobotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.Zone", "Zone")
                        .WithMany("RobotZones")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Robot");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.SemanticObject", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Map", "Map")
                        .WithMany("SemanticObjects")
                        .HasForeignKey("MapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ShelfLevel", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Aisle", "Aisle")
                        .WithMany("ShelfLevels")
                        .HasForeignKey("AisleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aisle");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ShelfScan", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Aisle", "Aisle")
                        .WithMany("ShelfScans")
                        .HasForeignKey("AisleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.Robot", "Robot")
                        .WithMany("ShelfScans")
                        .HasForeignKey("RobotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.ShelfLevel", "ShelfLevel")
                        .WithMany("ShelfScans")
                        .HasForeignKey("ShelfLevelID");

                    b.Navigation("Aisle");

                    b.Navigation("Robot");

                    b.Navigation("ShelfLevel");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ShoppingHistory", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Member", "Member")
                        .WithMany("ShoppingHistories")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Slot", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Product", "Product")
                        .WithMany("Slots")
                        .HasForeignKey("ProductID");

                    b.HasOne("SmartMarketBot.Domain.Entities.ShelfLevel", "ShelfLevel")
                        .WithMany("Slots")
                        .HasForeignKey("ShelfLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShelfLevel");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.SponsoredProduct", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Product", "Product")
                        .WithMany("SponsoredProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Staff", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("SmartMarketBot.Domain.Entities.Staff", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Subcategory", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Workstation", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.NavigationNode", "Node")
                        .WithMany("Workstations")
                        .HasForeignKey("NodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMarketBot.Domain.Entities.Zone", "Zone")
                        .WithMany("Workstations")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Zone", b =>
                {
                    b.HasOne("SmartMarketBot.Domain.Entities.Floor", "Floor")
                        .WithMany("Zones")
                        .HasForeignKey("FloorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Aisle", b =>
                {
                    b.Navigation("NavigationNodes");

                    b.Navigation("ShelfLevels");

                    b.Navigation("ShelfScans");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Floor", b =>
                {
                    b.Navigation("Maps");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.HealthTag", b =>
                {
                    b.Navigation("MemberHealthPreferences");

                    b.Navigation("ProductHealthTags");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Map", b =>
                {
                    b.Navigation("NavigationNodes");

                    b.Navigation("SemanticObjects");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Member", b =>
                {
                    b.Navigation("MemberHealthPreferences");

                    b.Navigation("ShoppingHistories");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.NavigationNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");

                    b.Navigation("RobotLogs");

                    b.Navigation("Workstations");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Product", b =>
                {
                    b.Navigation("HistoryItems");

                    b.Navigation("ProductHealthTags");

                    b.Navigation("PromotionProducts");

                    b.Navigation("RecipeItems");

                    b.Navigation("Slots");

                    b.Navigation("SponsoredProducts");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Promotion", b =>
                {
                    b.Navigation("PromotionProducts");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Robot", b =>
                {
                    b.Navigation("RobotLogs");

                    b.Navigation("RobotZones");

                    b.Navigation("ShelfScans");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ShelfLevel", b =>
                {
                    b.Navigation("ShelfScans");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.ShoppingHistory", b =>
                {
                    b.Navigation("HistoryItems");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Subcategory", b =>
                {
                    b.Navigation("ProductTypes");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Supermarket", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Member");

                    b.Navigation("Payments");

                    b.Navigation("Staff");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("SmartMarketBot.Domain.Entities.Zone", b =>
                {
                    b.Navigation("Aisles");

                    b.Navigation("RobotZones");

                    b.Navigation("Workstations");
                });
#pragma warning restore 612, 618
        }
    }
}
